normalize & abbreviate test result
fabriciorby/maven-surefire-junit5-tree-reporter pull request #2
Opened 2022-04-03 10:33 UTC by delanym

A parameterized test with a string array could produce up to 500 characters for the test result with newlines, tabs, etc. 180 seems like a balanced string length?

2022-04-03 23:04 UTC, fabriciorby commented
Hey @delanym, thanks for your PR!
Can you post an example of the problem this PR is solving?

2022-04-04 06:14 UTC, delanym commented
hi @fabriciorby you can see in https://github.com/delanym/junit5-samples the junit5-jupiter-starter-maven com.example.project.CalculatorTests

2022-06-25 20:38 UTC, fabriciorby requested changes

2022-06-25 20:38 UTC, fabriciorby commented on src/main/java/org/apache/maven/plugin/surefire/report/ConsoleTreeReporter.java
> +            String testResultShort = StringUtils.abbreviate(StringUtils.normalizeSpace(testResult.getReportName()), "\u2026", 180);
Hey! Can you please:
- Use constants for the code and number of characters?
- Make use of static import for `StringUtils`?

2022-06-25 20:39 UTC, fabriciorby commented
Hey, just got some time to test everything today.

Nice job! Dropped some comments.

2022-06-27 12:38 UTC, fabriciorby commented
Closing this because I've included your changes in the following PR.
https://github.com/fabriciorby/maven-surefire-junit5-tree-reporter/pull/11

2022-06-27 12:38 UTC, closed without merging